# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InventoryItem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from service import Book_pb2 as Book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13InventoryItem.proto\x12\rinventoryitem\x1a\nBook.proto\"r\n\rInventoryItem\x12\x14\n\x0cinventoryNum\x18\x01 \x01(\x05\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.inventoryitem.Status\x12\x1b\n\x05\x61\x42ook\x18\x03 \x01(\x0b\x32\n.book.BookH\x00\x42\x07\n\x05types*H\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x14\n\x10STATUS_AVAILABLE\x10\x01\x12\x10\n\x0cSTATUS_TAKEN\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InventoryItem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=166
  _STATUS._serialized_end=238
  _INVENTORYITEM._serialized_start=50
  _INVENTORYITEM._serialized_end=164
# @@protoc_insertion_point(module_scope)
